### ISSUE TITLE
 《Relational decomposition for program synthesis》 The most promising way to solve the ARC-AGI problem

### ISSUE THREAD

**Issue by zdx3578** [logic-and-learning-lab/ecai23-combo#3]
in 《Relational decomposition for program synthesis 》 ARGA use paired-node，if use hyperedge, 连续相同颜色节点为一个对象，可以提高对象操作效率， 我提取了相同颜色节点为一个超变
ILP 可以轻松表示超变hyperedge多节点

另外 fig 1 的rule

out(X,Y,yellow):- empty(X,Y), height(X). 是不是应该高度1
out(X,Y,yellow):- empty(X,Y), height(**1**).

**Comment by andrewcropper** [comment]
What is the question?
