### ISSUE TITLE
running seem not normal ?

### ISSUE THREAD

**Issue by zdx3578** [logic-and-learning-lab/ecai23-combo#4]
(base) ➜  VSAHDC  cd /home/zdx/github/VSAHDC ; /usr/bin/env /home/zdx/miniconda3/envs/py312/bin/python /ho
me/zdx/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../
debugpy/launcher 46139 -- /home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py train 
/home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py:946: SyntaxWarning: invalid escape sequence '\m'
  x += '\midrule\n'
/home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py:948: SyntaxWarning: invalid escape sequence '\_'
  renamed = task.replace('iggp-', '').replace('_','\_')
/home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py:950: SyntaxWarning: invalid escape sequence '\_'
  renamed = renamed.replace('adjacent\_to\_red', 'adj\_red')
/home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py:950: SyntaxWarning: invalid escape sequence '\_'
  renamed = renamed.replace('adjacent\_to\_red', 'adj\_red')
/home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py:952: SyntaxWarning: invalid escape sequence '\_'
  renamed = renamed.replace('graph\_colouring', 'colouring')
/home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py:953: SyntaxWarning: invalid escape sequence '\_'
  renamed = renamed.replace('undirected\_edge', 'undirected')
/home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py:954: SyntaxWarning: invalid escape sequence '\_'
  renamed = renamed.replace('two\_children', '2children')
/home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py:971: SyntaxWarning: invalid escape sequence '\p'
  x += ' & \\textbf{' + str(value) + ' $\pm$ ' + str(err) + '} '
/home/zdx/github/VSAHDC/ilp/ecai23-combo/benchmark.py:973: SyntaxWarning: invalid escape sequence '\p'

...................

def popper(settings, queue):
    if settings.bkcons:
        deduce_bk_cons(settings)

    tester = Tester(settings)    (**exit in this step** )  and opendebug no infomation

10:37:25 Max rules: 1
10:37:25 Max vars: 6
10:37:30 Max body: 6
10:37:47 TRAIN aleph: task:trains3       timeout:3600    trial:1
10:37:47 TRAIN metagol: task:trains3     timeout:3600    trial:1

ERROR: source_sink `metagol' does not exist
ERROR: source_sink `metarules' does not exist
ERROR: source_sink `'data/trains3/data/train/1.pl'' does not exist

ERROR: Unknown procedure: run/0 (DWIM could not correct goal)
10:37:53 TRAIN popper: task:trains3      timeout:3600    trial:1
10:37:56 TRAIN dcc: task:trains3         timeout:3600    trial:1
10:37:56 TRAIN popper2: task:trains3     timeout:3600    trial:1
10:37:59 Max rules: 1
10:37:59 Max vars: 6
10:38:01 Max body: 6
10:38:08 TRAIN aleph: task:trains4       timeout:3600    trial:1
10:38:08 TRAIN metagol: task:trains4     timeout:3600    trial:1

ERROR: source_sink `metagol' does not exist
ERROR: source_sink `metarules' does not exist
ERROR: source_sink `'data/trains4/data/train/1.pl'' does not exist

ERROR: Unknown procedure: run/0 (DWIM could not correct goal)
10:38:09 TRAIN popper: task:trains4      timeout:3600    trial:1
10:38:12 TRAIN dcc: task:trains4         timeout:3600    trial:1
10:38:12 TRAIN popper2: task:trains4     timeout:3600    trial:1
10:38:14 Max rules: 1
10:38:14 Max vars: 6
10:38:15 Max body: 6

but when run  [Popper](https://github.com/logic-and-learning-lab/Popper)  debug log is normal

f(V0):- has_car(V0,V1),has_car(V0,V5),has_car(V0,V4),has_car(V0,V3),rectangle(V2),has_load(V1,V2).
Program 2237:
f(V0):- has_car(V0,V1),has_car(V0,V5),has_car(V0,V4),has_car(V0,V3),two_wheels(V1),has_load(V1,V2).
Program 2238:
f(V0):- has_car(V0,V1),has_car(V0,V5),has_car(V0,V4),has_car(V0,V3),has_load(V1,V2),triangle(V2).
Program 2239:
f(V0):- has_car(V0,V1),has_load(V5,V2),has_car(V0,V5),has_car(V0,V4),short(V5),has_car(V0,V3).
Program 2240:
f(V0):- has_car(V0,V1),roof_open(V3),has_car(V0,V2),roof_open(V2),roof_open(V1),has_car(V0,V3).
Program 2241:
f(V0):- has_car(V0,V1),roof_open(V3),has_car(V0,V2),roof_open(V2),has_car(V0,V4),has_car(V0,V3).
Program 2242:
f(V0):- has_car(V0,V1),has_car(V0,V2),has_car(V0,V4),has_car(V0,V3),short(V4),short(V3).
Program 2243:
f(V0):- has_car(V0,V1),has_car(V0,V2),has_car(V0,V4),has_car(V0,V3),short(V4),two_wheels(V3).
Program 2244:
f(V0):- has_car(V0,V1),has_car(V0,V2),has_car(V0,V4),has_car(V0,V3),two_wheels(V2),two_wheels(V3).
Program 2245:
f(V0):- has_car(V0,V1),has_car(V0,V2),has_car(V0,V3),two_wheels(V2),two_wheels(V1),two_wheels(V3).
Program 2246:
f(V0):- has_car(V0,V1),has_car(V0,V2),has_car(V0,V3),two_wheels(V2),two_wheels(V1),short(V3).
Program 2247:
f(V0):- has_car(V0,V1),short(V1),has_car(V0,V2),has_car(V0,V3),two_wheels(V2),short(V3).
Program 2248:
f(V0):- has_car(V0,V1),short(V2),short(V1),has_car(V0,V2),has_car(V0,V3),short(V3).
********** SOLUTION **********
Precision:1.00 Recall:1.00 TP:792 FN:0 TN:208 FP:0 Size:17
f(V0):- has_car(V0,V1),roof_open(V1),has_load(V1,V2),three_load(V2).
f(V0):- has_car(V0,V1),roof_open(V1),has_car(V0,V2),roof_closed(V2).
f(V0):- has_car(V0,V4),has_load(V4,V2),triangle(V2),has_car(V0,V3),has_load(V3,V1),rectangle(V1).
******************************
Num. programs: 2248
Test:
        Called: 2248 times       Total: 1.44     Mean: 0.0006    Max: 0.003      Percentage: 44%
Constrain:
        Called: 2248 times       Total: 0.67     Mean: 0.0003    Max: 0.030      Percentage: 20%
Bkcons:
        Called: 1 times          Total: 0.38     Mean: 0.3850    Max: 0.385      Percentage: 11%
Recalls:
        Called: 1 times          Total: 0.29     Mean: 0.2883    Max: 0.288      Percentage: 8%
Load Data:
        Called: 1 times          Total: 0.19     Mean: 0.1856    Max: 0.186      Percentage: 5%
Generate:
        Called: 2249 times       Total: 0.16     Mean: 0.0001    Max: 0.007      Percentage: 4%

**Comment by andrewcropper** [comment]
Sorry, what is the question?

**Comment by zdx3578** [comment]
ecai23-combo/benchmark.py train    **run error**

def popper(settings, queue):
if settings.bkcons:
deduce_bk_cons(settings)

tester = Tester(settings)    (   **Seems to fail at this step.**    )

https://github.com/logic-and-learning-lab/Popper is updated ( https://github.com/logic-and-learning-lab/ecai23-combo/issues/5 )， i  will use Popper
