### ISSUE TITLE
what diff this repo and https://github.com/logic-and-learning-lab/Popper

### ISSUE THREAD

**Issue by zdx3578** [logic-and-learning-lab/ecai23-combo#5]
in popper release :  
[v2.0.0](https://github.com/logic-and-learning-lab/Popper/releases/tag/v2.0.0)
A new version of Popper

The main change is a more efficient way of learning programs with multiple rules, especially non-recursive programs as described Learning programs by combining programs, https://arxiv.org/abs/2206.01614

is in  https://github.com/logic-and-learning-lab/Popper the [combo] is update ?

popper run  iggp-coins-goal  just 14s below in paper, like popper repo is update

**Comment by andrewcropper** [comment]
Hi, 

Popper includes the update from that paper.

Kind regards,

Andrew
